
export const cards = [
    {
        id: 0,
        name: 'The Fool',
        description: 'The image of new beginnings, innocence, and adventure.  A new opportunity, journey, or relationship.',
        image: "https://d2lc40okpdverw.cloudfront.net/fool.png",
    },
    {
        id: 1,
        name: 'The Magician',
        description: 'Transformation and major life change. It predicts that you will be able to make a big change in your life, and that this change will be for the better. This is a great card to get if you are feeling stuck in a rut and need some fresh start.',
        image: "https://d2lc40okpdverw.cloudfront.net/magician.png",
    },
    {
        id: 2,
        name: 'The High Priestess',
        description: 'Mystery and intuition. It is a beautiful card that represents the feminine side of the divine. The High Priestess is a wise and compassionate woman who is able to see into the future. ',
        image: "https://d2lc40okpdverw.cloudfront.net/highpriestess.png",
    },
    {
        id: 3,
        name: 'The Empress',
        description: 'Creation and nurturing. It predicts a future of abundance and fertility, with plenty of opportunities for growth and expansion.',
        image: "https://d2lc40okpdverw.cloudfront.net/empress.png",
    },
    {
        id: 4,
        name: 'The Emperor',
        description: 'Power and conquering. It predicts that you will have the strength and power to overcome any obstacle in your way. You will be able to achieve anything you set your mind to.',
        image: "https://d2lc40okpdverw.cloudfront.net/emperor.png",
     },
    {
        id: 5,
        name: 'The Hierophant',
        description: 'Traditional wisdom and knowledge for the future. It is a beautiful card that represents the importance of learning and understanding the past in order to make the future brighter.',
        image: "https://d2lc40okpdverw.cloudfront.net/hierophant.png",
     },
    {
        id: 6,
        name: 'The Lovers',
        description: 'Love and romance. Romantic bliss and joyful fulfillment in a new relationship or renewed passion in an existing relationship.',
        image: "https://d2lc40okpdverw.cloudfront.net/lovers.png",
    },
    {
        id: 7,
        name: 'The Chariot',
        description: 'Victory and great things for the future. It represents success, victory, and triumph. It is a card of strength and determination. The Chariot is a force to be reckoned with. It is a sign of good things to come.',
        image: "https://d2lc40okpdverw.cloudfront.net/chariot.png",
    },
    {
        id: 8,
        name: 'Strength',
        description: 'Great strength and fortitude in the face of adversity. With this card comes the ability to overcome any obstacle and the courage to face any challenge. The Strength tarot card is a reminder that we are all capable of great things if we set our minds to it.',
        image: "https://d2lc40okpdverw.cloudfront.net/strength.png",
    },
    {
        id: 9,
        name: 'The Hermit',
        description: 'Introspection and self-reflection. It is a time to take stock of your life and figure out what is truly important to you. This can be a difficult and challenging process, but it is also a time of great personal growth. ',
        image: "https://d2lc40okpdverw.cloudfront.net/hermit.png",
    },
    {
        id: 10,
        name: 'The Wheel of Fortune',
        description: 'Change, new beginnings, and the cyclical nature of life. It is a reminder that nothing stays the same forever, and that good fortune and bad fortune are both part of the human experience. The Wheel of Fortune is a reminder to stay flexible and open to change, as it is the only constant in life.',
        image: "https://d2lc40okpdverw.cloudfront.net/wheeloffortune.png",
     },
    {
        id: 11,
        name: 'Justice',
        description: 'Balance, harmony, and fairness. It predicts that the future will bring these things into your life in some way. Justice is about making things right, and this card suggests that you will be able to do that in your own life.',
        image: "https://d2lc40okpdverw.cloudfront.net/justice.png",
    },
    {
        id: 12,
        name: 'The Hanged Man',
        description: 'One is caught between two choices. It is a time of indecision and confusion. This card advises you to take a step back, to look at the bigger picture, and to be patient. The Hanged Man also suggests that you let go of what is no longer serving you. This is a time of transition and rebirth.',
        image: "https://d2lc40okpdverw.cloudfront.net/hangedman.png",
     },
    {
        id: 13,
        name: 'Death',
        description: 'Death, rebirth, change, and transformation. It suggests that something major is ending in your life, but also that new beginnings are on the horizon. This could be a time of great upheaval, but also of great opportunity. The future looks bright, but it will be full of challenges and obstacles to overcome.',
        image: "https://d2lc40okpdverw.cloudfront.net/death.png",
    },
    {
        id: 14,
        name: 'Temperance',
        description: 'Balance and harmony in life. It is about learning to control your emotions and not letting them control you. This card predicts that you will find a way to strike a perfect balance in your life, and that you will be able to control your destiny.',
        image: "https://d2lc40okpdverw.cloudfront.net/temperance.png",
     },
    {
        id: 15,
        name: 'The Devil',
        description: 'Fears, addictions, and desires. It urges us to face our demons and to overcome them. The card predicts that we will be challenged in the future, but we have the strength to overcome these obstacles.',
        image: "https://d2lc40okpdverw.cloudfront.net/devil.png",
      },
    {
        id: 16,
        name: 'The Tower',
        description: 'Great upheaval and chaos in the future. The meaning of the card is that everything will come crashing down, but from the rubble will rise a new and better version of yourself.',
        image: "https://d2lc40okpdverw.cloudfront.net/tower.png",
    },
    {
        id: 17,
        name: 'The Star',
        description: 'Hope, faith, and endless possibility. It predicts that good things are on the horizon, and that your wishes may come true. This is a time to have faith in yourself and your abilities, as success is within reach. The future looks bright and full of potential, so let your light shine and reach for the stars.',
        image: "https://d2lc40okpdverw.cloudfront.net/star.png",
    },
    {
        id: 18,
        name: 'The Moon',
        description: 'Secrets, mysteries, intuition, and psychic ability. It predicts that the future will be full of surprises and you will need to rely on your intuition to guide you. The Moon also represents imagination, so expect your future to be full of creativity and new ideas.',
        image: "https://d2lc40okpdverw.cloudfront.net/moon.png",
    },
    {
        id: 19,
        name: 'The Sun',
        description: 'Joy, fulfillment, happiness, and success. It is a symbol of good fortune and represents the power of the sun to bring positive change. The Sun is a positive card that suggests that the querent will achieve their goals and enjoy good health and fortune.',
        image: "https://d2lc40okpdverw.cloudfront.net/sun.png",
    },
    {
        id: 20,
        name: 'Judgement',
        description: 'Actions have consequences. It predicts that we will be called to account for our choices in the future, and that we must be prepared to face the consequences of our actions.',
        image: "https://d2lc40okpdverw.cloudfront.net/judgement.png",
      },
    {
        id: 21,
        name: 'The World',
        description: 'The fulfillment of something great.  The future will be full of new and wonderful experiences. The world is a place full of possibility and hope, and this card predicts that the future will be full of possibilities for everyone.',
        image: "https://d2lc40okpdverw.cloudfront.net/world.png",
     },
    {
        id: 22,
        name: 'Ace of Wands',
        description: 'New beginnings, creativity, and fertility. It is a positive card that suggests new opportunities and exciting times ahead.',
        image: "https://d2lc40okpdverw.cloudfront.net/1wands.png",
     },
    {
        id: 23,
        name: 'Two of Wands',
        description: 'The potential for success and the ability to make your dreams a reality. It is a positive card that suggests that your hard work and determination will pay off in the end. ',
        image: "https://d2lc40okpdverw.cloudfront.net/2wands.png",
     },
    {
        id: 24,
        name: 'Three of Wands',
        description: 'Foresight and planning. It suggests that the querent take a moment to consider their options and make a decision about their future. This card can also represent a time of new beginnings, and so it is a good omen for predicting the future.',
        image: "https://d2lc40okpdverw.cloudfront.net/3wands.png",
    },
    {
        id: 25,
        name: 'Four of Wands',
        description: 'Good things are on the horizon. If you have been working hard towards a goal, the four of wands suggests that your efforts will pay off and you will reap the rewards. This is a time to enjoy your accomplishments and to feel proud of what you have achieved.',
        image: "https://d2lc40okpdverw.cloudfront.net/4wands.png",
     },
    {
        id: 26,
        name: 'Five of Wands',
        description: 'Obstacles and challenges.  It suggests that you will have to face some difficulties in your future, but you will be able to overcome them.',
        image: "https://d2lc40okpdverw.cloudfront.net/5wands.png",
       },
    {
        id: 27,
        name: 'Six of Wands',
        description: 'Victory and success. It suggests that you have the strength and ability to overcome any obstacles in your path, and that you will be victorious in any undertaking.',
        image: "https://d2lc40okpdverw.cloudfront.net/6wands.png",
     },
    {
        id: 28,
        name: 'Seven of Wands',
        description: 'Vicotry is near. It is a time to stand your ground and defend what is yours. This card can also suggest that there are still some challenges to be faced before you can claim your prize.',
        image: "https://d2lc40okpdverw.cloudfront.net/7wands.png",
    },
    {
        id: 29,
        name: 'Eight of Wands',
        description: 'Movement and change.  It suggests that something is about to happen or is already in motion. This change may be positive or negative, but it is likely to be fast and exciting.',
        image: "https://d2lc40okpdverw.cloudfront.net/8wands.png",
     },
    {
        id: 30,
        name: 'Nine of Wands',
        description: 'Resilience and tenacity. It suggests that whatever challenges you are facing, you have the strength and determination to overcome them. This card can also indicate that you may need to take a stand and defend yourself or your beliefs. ',
        image: "https://d2lc40okpdverw.cloudfront.net/9wands.png",
     },
    {
        id: 31,
        name: 'Ten of Wands',
        description: 'Someone is carrying a burden that is too heavy. This may be a physical burden, or it may be an emotional one. Either way, it is important to find a way to lighten your load. This card can also suggest that you are taking on too much responsibility. Try to delegate some of your tasks to others.',
        image: "https://d2lc40okpdverw.cloudfront.net/10wands.png",
    },
    {
        id: 32,
        name: 'Page of Wands',
        description: 'New beginnings, excitement and adventure. It is a card that predicts good news and a time of positive change. This is a time to take risks, to follow your dreams and to seize opportunities. The future looks bright and full of potential.',
        image: "https://d2lc40okpdverw.cloudfront.net/11wands.png",
     },
    {
        id: 33,
        name: 'Knight of Wands',
        description: 'Good news and great opportunities in the future. This is a time to seize opportunities and make the most of your talents. You will be able to accomplish a lot and achieve success.',
        image: "https://d2lc40okpdverw.cloudfront.net/12wands.png",
    },
    {
        id: 34,
        name: 'Queen of Wands',
        description: 'Passion, creativity, and determination. The Queen of Wands is a powerful force that will guide you to your goals. You will be able to achieve anything you set your mind to.',
        image: "https://d2lc40okpdverw.cloudfront.net/13wands.png",
     },
    {
        id: 35,
        name: 'King of Wands',
        description: 'Powerful force, representing willpower and determination. When this card appears in a tarot reading, it suggests that the querent has the power to manifest their desires and create their own destiny. This is a positive card that predicts success and good fortune in the future.',
        image: "https://d2lc40okpdverw.cloudfront.net/14wands.png",
     },
    {
        id: 36,
        name: 'The Ace of Cups',
        description: 'New beginnings, love, and happiness. It is a very positive card that predicts good things to come in the future. If you are seeking a new relationship, the Ace of Cups is a great card to get. It indicates that you will find true love and happiness in your new relationship.',
        image: "https://d2lc40okpdverw.cloudfront.net/1cups.png",
     },
    {
        id: 37,
        name: 'The Two of Cups',
        description: 'Love and relationships. It can represent a new relationship, or a strong, existing one. This card can also indicate a need for balance and harmony in a relationship. If you are single, the Two of Cups can represent a new love interest.',
        image: "https://d2lc40okpdverw.cloudfront.net/2cups.png",
      },
    {
        id: 38,
        name: 'The Three of Cups',
        description: 'Celebration and joy. This is a time to come together with others and enjoy the good things in life. It is a positive card that predicts happy times ahead, full of love, friendship, and good fortune.',
        image: "https://d2lc40okpdverw.cloudfront.net/3cups.png",
     },
    {
        id: 39,
        name: 'The Four of Cups',
        description: 'Someone is not paying attention to what is happening around them. This can be a warning for the future, suggesting that the person needs to be more aware of their surroundings in order to avoid potential problems.',
        image: "https://d2lc40okpdverw.cloudfront.net/4cups.png",
     },
    {
        id: 40,
        name: 'The Five of Cups',
        description: 'A sign of loss. However, this is not always the case. The Five of Cups can also be seen as a sign of change. This change can be either good or bad, but it is often seen as a positive change.',
        image: "https://d2lc40okpdverw.cloudfront.net/5cups.png",
    },
    {
        id: 41,
        name: 'The Six of Cups',
        description: 'Nostalgia and looking back on happy memories. It is a reminder that good times have been had in the past, and that although the future may be uncertain, it is important to hold onto the positive things from the past. This card can also indicate that someone from the past may reappear.',
        image: "https://d2lc40okpdverw.cloudfront.net/6cups.png",
      },
    {
        id: 42,
        name: 'The Seven of Cups',
        description: 'Choices. You will be presented with many opportunities in your future and it will be up to you to choose which path to take. You may be faced with a difficult decision that will require some soul-searching. This is a time to trust your gut and go with your heart.',
        image: "https://d2lc40okpdverw.cloudfront.net/7cups.png",
     },
    {
        id: 43,
        name: 'The Eight of Cups',
        description: 'Leaving something behind. It suggests that it may be time to move on from a situation or relationship that is no longer working. This may be a difficult decision, but it is one that will ultimately lead to a better future.',
        image: "https://d2lc40okpdverw.cloudfront.net/8cups.png",
    },
    {
        id: 44,
        name: 'The Nine of Cups',
        description: 'Happiness, contentment, and satisfaction. It is a card that predicts that your future will be one of happiness and contentment. You will be able to enjoy your life and all that it has to offer. This is a positive card that predicts a bright future.',
        image: "https://d2lc40okpdverw.cloudfront.net/9cups.png",
     },
    {
        id: 45,
        name: 'The Ten of Cups',
        description: 'Happiness, contentment, and fulfilled dreams. This card indicates that your Cup is full and you are ready to enjoy all that life has to offer. You have reached a point where you are able to see the beauty in everyday life and appreciate all that you have. ',
        image: "https://d2lc40okpdverw.cloudfront.net/10cups.png",
    },
    {
        id: 46,
        name: 'The Page of Cups',
        description: 'New beginnings and new possibilities. It represents a time of change and growth, and predicts that good things are on the horizon. This is a card of hope and happiness, and suggests that your future is full of potential.',
        image: "https://d2lc40okpdverw.cloudfront.net/11cups.png",
     },
    {
        id: 47,
        name: 'The Knight of Cups',
        description: 'Beginnings and new possibilities. It is a card of hope and change, and can indicate that good things are on the horizon. This card can be a positive sign for predicting the future, as it suggests that new opportunities and experiences are on the way.',
        image: "https://d2lc40okpdverw.cloudfront.net/12cups.png",
      },
    {
        id: 48,
        name: 'The Queen of Cups',
        description: 'A kind and compassionate nature. She is a loving wife and mother, and is often a good friend. She is also a very intuitive person, and is often able to see the best in people. This card can represent a time of emotional healing, and can also suggest that you will be able to find happiness in your relationships.',
        image: "https://d2lc40okpdverw.cloudfront.net/13cups.png",
     },
    {
        id: 49,
        name: 'The King of Cups',
        description: 'Emotional balance and calm. It suggests that you are in control of your emotions and are able to see both sides of any situation. This card predicts that you will be able to maintain your composure in the face of adversity and come out ahead.',
        image: "https://d2lc40okpdverw.cloudfront.net/14cups.png",
     },
    {
        id: 50,
        name: 'The Ace of Swords',
        description: 'Victory, triumph, and conquering all obstacles. It is a very positive card that predicts success in all areas of life. The Ace of Swords also suggests that you have the strength and power to overcome any challenges that come your way.',
        image: "https://d2lc40okpdverw.cloudfront.net/1swords.png",
     },
    {
        id: 51,
        name: 'The Two of Swords',
        description: 'A crossroads. You may be feeling pulled in two different directions and struggling to make a decision. This can be a difficult time, but it is also a time when you have the opportunity to learn and grow.',
        image: "https://d2lc40okpdverw.cloudfront.net/2swords.png",
     },
    {
        id: 52,
        name: 'The Three of Swords',
        description: 'Heartbreak and pain. It can represent the end of a relationship or a difficult time in your life. This card can also suggest that you are feeling lost and alone. However, the Three of Swords can also represent the beginning of a new chapter in your life. ',
        image: "https://d2lc40okpdverw.cloudfront.net/3swords.png",
     },
    {
        id: 53,
        name: 'The Four of Swords',
        description: 'Rest and recovery. It is a time to take a break from the chaos and noise of the world and to retreat into your own inner world. This is a time to reflect on your life and to find a new perspective. The Four of Swords is a time to be still and to listen to your heart.',
        image: "https://d2lc40okpdverw.cloudfront.net/4swords.png",
    },
    {
        id: 54,
        name: 'The Five of Swords',
        description: 'Difficult times ahead, but you have the strength and resilience to overcome them. You may need to take a stand and defend yourself, but ultimately you will triumph. This card also suggests that it may be time to let go of the past and move on.',
        image: "https://d2lc40okpdverw.cloudfront.net/5swords.png",
     },
    {
        id: 55,
        name: 'The Six of Swords',
        description: 'Moving on from a difficult situation. This card can also represent a period of transition, such as moving to a new home or starting a new job. You may be leaving something behind, but you will be moving on to something better. ',
        image: "https://d2lc40okpdverw.cloudfront.net/6swords.png",
    },
    {
        id: 56,
        name: 'The Seven of Swords',
        description: 'Someone feels overwhelmed and outnumbered. They may feel like they are constantly fighting and that they cannott win. This card can also indicate that someone is trying to take on too much and they need to take a step back.',
        image: "https://d2lc40okpdverw.cloudfront.net/7swords.png",
     },
    {
        id: 57,
        name: 'The Eight of Swords',
        description: 'One is trapped by their own negative thoughts. You may feel like you cannot see a way out of your current situation. It is time to break free from your mental prison and see the truth.',
        image: "https://d2lc40okpdverw.cloudfront.net/8swords.png",
    },
    {
        id: 58,
        name: 'The Nine of Swords',
        description: 'Despair and suffering. It suggests that someone is in a state of mental anguish and is feeling overwhelmed by their circumstances. This card can indicate that someone is facing a major challenge or crisis in their life.',
        image: "https://d2lc40okpdverw.cloudfront.net/9swords.png",
     },
    {
        id: 59,
        name: 'The Ten of Swords',
        description: 'Finality and completion. It is a marker of an ending, and signifies that all that can be done has been done.',
        image: "https://d2lc40okpdverw.cloudfront.net/10swords.png",
    },
    {
        id: 60,
        name: 'The Page of Swords',
        description: 'A tough decision. This decision will have far-reaching consequences and will be difficult to make.',
        image: "https://d2lc40okpdverw.cloudfront.net/11swords.png",
     },
    {
        id: 61,
        name: 'The Knight of Swords',
        description: 'Triumph in any battle or challenge. You are brave and have the courage to face anything head on. This card also predicts that you will be successful in any undertaking.',
        image: "https://d2lc40okpdverw.cloudfront.net/12swords.png",
     },
    {
        id: 62,
        name: 'The Queen of Swords',
        description: 'Strength, courage, and determination. This card can be a great predictor of success in any future endeavors. The Queen of Swords is also a reminder that we must be careful not to cut ourselves off from our emotions, as they can be our greatest ally..',
        image: "https://d2lc40okpdverw.cloudfront.net/13swords.png",
     },
    {
        id: 63,
        name: 'The King of Swords',
        description: 'You will get what you want. You will be able to achieve your goals and make your dreams come true. This is a time to be decisive and take action. Be confident and stay focused on your goals. You will be able to achieve great things..',
        image: "https://d2lc40okpdverw.cloudfront.net/14swords.png",
    },
    {
        id: 64,
        name: 'The Ace of Coins',
        description: 'Prosperity and good fortune. If you are asking about your future, this tarot card is a very positive sign that predicts success in whatever you pursue.',
        image: "https://d2lc40okpdverw.cloudfront.net/1coins.png",
    },
    {
        id: 65,
        name: 'The Two of Coins',
        description: 'Balance and harmony. It is a positive card that suggests that you are able to maintain a sense of equilibrium in your life. You may be able to find success in your endeavors by working hard and maintaining a sense of focus.',
        image: "https://d2lc40okpdverw.cloudfront.net/2coins.png",
      },
    {
        id: 66,
        name: 'The Three of Coins',
        description: 'Hard work is paying off. If you put in the effort, you will be rewarded. The Three of Coins can also be a sign of good luck.',
        image: "https://d2lc40okpdverw.cloudfront.net/3coins.png",
     },
    {
        id: 67,
        name: 'The Four of Coins',
        description: 'Security and abundance. You have worked hard to create a stable foundation and it shows. This is a time to enjoy your achievements and reap the rewards of your labour. ',
        image: "https://d2lc40okpdverw.cloudfront.net/4coins.png",
     },
    {
        id: 68,
        name: 'The Five of Coins',
        description: 'Difficult times ahead. It suggests that you will face challenges and obstacles, but you have the strength and resilience to overcome them. This card also suggests that you will be supported by your friends and family during these difficult times.',
        image: "https://d2lc40okpdverw.cloudfront.net/5coins.png",
     },
    {
        id: 69,
        name: 'The Six of Coins',
        description: 'Good fortune in the future. It is a positive card that suggests that the querent will be financially successful. This card also suggests that the querent will be able to help others with their money and resources.',
        image: "https://d2lc40okpdverw.cloudfront.net/6coins.png",
    },
    {
        id: 70,
        name: 'The Seven of Coins',
        description: 'Good luck with your finances and career in the near future. You will be able to achieve your goals and enjoy a prosperous life. This is a great card to have in a tarot reading if you are hoping for a positive outcome regarding your money or work.',
        image: "https://d2lc40okpdverw.cloudfront.net/7coins.png",
     },
    {
        id: 71,
        name: 'The Eight of Coins',
        description: 'Good fortune in the future. This card suggests that you will be rewarded for your hard work and that you will be able to enjoy the fruits of your labour. This is a positive card that indicates that you will be able to achieve your goals and that you will be prosperous.',
        image: "https://d2lc40okpdverw.cloudfront.net/8coins.png",
     },
    {
        id: 72,
        name: 'The Nine of Coins',
        description: 'Prosperity and abundance. It is a positive card that predicts success in business and financial ventures. This card also suggests that the querent will be able to enjoy their material possessions and live a comfortable life.',
        image: "https://d2lc40okpdverw.cloudfront.net/9coins.png",
    },
    {
        id: 73,
        name: 'The Ten of Coins',
        description: 'Financial security in the future. This card suggests that the querent will have a comfortable and stable financial situation. This card can also suggest that the querent will inherit money or property in the future.',
        image: "https://d2lc40okpdverw.cloudfront.net/10coins.png",
     },
    {
        id: 74,
        name: 'The Page of Coins',
        description: 'Good news and positive change in the future. This card suggests that your financial situation is about to improve, and that you will be able to achieve your goals with hard work and perseverance.',
        image: "https://d2lc40okpdverw.cloudfront.net/11coins.png",
     },
    {
        id: 75,
        name: 'The Knight of Coins',
        description: 'Hard work in order to achieve success. This card suggests that you will need to be patient and diligent in order to reach your goals. The Knight of Coins can also indicate that you will receive help from someone who is more experienced than you.',
        image: "https://d2lc40okpdverw.cloudfront.net/12coins.png",
      },
    {
        id: 76,
        name: 'The Queen of Coins',
        description: 'Prosperity, abundance, and fertility. If you are asking about a specific area of your life, this card can represent financial stability and success. If you are wondering about your love life, the Queen of Coins can predict a happy and prosperous relationship..',
        image: "https://d2lc40okpdverw.cloudfront.net/13coins.png",
      },
    {
        id: 77,
        name: 'The King of Coins',
        description: 'Prosperity and abundance. In a tarot reading, this card can indicate that financial success is on the horizon. The King is a generous and generous ruler, so this card can also indicate that you will be able to give and receive generously in the future..',
        image: "https://d2lc40okpdverw.cloudfront.net/14coins.png",
     },
     {
        id: 78,
        name: 'The Fool, reversed',
        description: 'Foolishness.  Danger.  A risky situation.  Someone is playing with fire or being taken advantage of.',
        image: "https://d2lc40okpdverw.cloudfront.net/foolr.png",
    },
    {
        id: 79,
        name: 'The Magician, reversed',
        description: 'Manipulation or missed opportunities.  Someone is harming others to get what they want, or they have missed a chance to change for the better.',
        image: "https://d2lc40okpdverw.cloudfront.net/magicianr.png",
    },
    {
        id: 80,
        name: 'The High Priestess, reversed',
        description: 'Inner doubt and confusion.  One is out of touch with inner wisdom and intuition. At worst, a powerful figure will be exposed as a fraud. ',
        image: "https://d2lc40okpdverw.cloudfront.net/highpriestessr.png",
    }, 
    {
        id: 81,
        name: 'The Empress, reversed',
        description: 'Misfortune and missed opportunities.  Lack of creativity and inspiration, or at worst, depression and despair.',
        image: "https://d2lc40okpdverw.cloudfront.net/empressr.png",
    },
    {
        id: 82,
        name: 'The Emperor, reversed',
        description: 'The Emperor card is all about power and conquering. It predicts that you will have the strength and power to overcome any obstacle in your way. You will be able to achieve anything you set your mind to.',
        image: "https://d2lc40okpdverw.cloudfront.net/emperorr.png",
     },
    {
        id: 83,
        name: 'The Hierophant, reversed',
        description: 'Rebellion and frustration.  Old ways are no longer working.  One must question everything and forge your own path in life.',
        image: "https://d2lc40okpdverw.cloudfront.net/hierophantr.png",
     },
    {
        id: 84,
        name: 'The Lovers, reversed',
        description: 'An unhappy relationship.  Arguments, breakups, or infidelity.  Commitment issues, lack of communication, or being with the wrong person.',
        image: "https://d2lc40okpdverw.cloudfront.net/loversr.png",
    },
    {
        id: 85,
        name: 'The Chariot, reversed',
        description: 'Chaos and confusion.  A situation is out of control.  One is pulled in many different directions but cannot make a decision.',
        image: "https://d2lc40okpdverw.cloudfront.net/chariotr.png",
    },
    {
        id: 86,
        name: 'Strength, reversed',
        description: 'Someone is facing challenges they do not know how to overcome.  One is acting out of fear or anger rather than strength.',
        image: "https://d2lc40okpdverw.cloudfront.net/strengthr.png",
    },
    {
        id: 87,
        name: 'The Hermit, reversed',
        description: 'Loneliness and isolation.  Avoiding something due to fear, insecurity, or confusion. It is time for personal reflection and change.',
        image: "https://d2lc40okpdverw.cloudfront.net/hermitr.png",
    },
    {
        id: 88,
        name: 'The Wheel of Fortune, reversed',
        description: 'Bad luck or setbacks.  But not forever -- if you are patient and persevere, the good times will return.',
        image: "https://d2lc40okpdverw.cloudfront.net/wheeloffortuner.png",
     },
    {
        id: 89,
        name: 'Justice, reversed',
        description: 'Injustice.  Someone is wrongfully accused or treated unfairly.  But truth will come out soon and you will be vindicated.',
        image: "https://d2lc40okpdverw.cloudfront.net/justicer.png",
    },
    {
        id: 90,
        name: 'The Hanged Man, reversed',
        description: 'A need for change and rebirth.  It is time to move on and discover new opportunities in your life.',
        image: "https://d2lc40okpdverw.cloudfront.net/hangedmanr.png",
     },
    {
        id: 91,
        name: 'Death, reversed',
        description: 'Frightening, powerful, intense change.  Although you may be afraid, this is a transformational rebirth and a new beginning.',
        image: "https://d2lc40okpdverw.cloudfront.net/deathr.png",
    },
    {
        id: 92,
        name: 'Temperance, reversed',
        description: 'Temptation and addiction.  You are tempted to give into something you know you should not do.',
        image: "https://d2lc40okpdverw.cloudfront.net/temperancer.png",
     },
    {
        id: 93,
        name: 'The Devil, reversed',
        description: 'Overcoming your demons.  One has broken free of temptation and harmful habits to create a new and better life.',
        image: "https://d2lc40okpdverw.cloudfront.net/devilr.png",
      },
    {
        id: 94,
        name: 'The Tower, reversed',
        description: 'Chaos and upheaval.  Your world is shaken by a major life change.  Weather the storm, and you will survive the impending crisis or change.',
        image: "https://d2lc40okpdverw.cloudfront.net/towerr.png",
    },
    {
        id: 95,
        name: 'The Star, reversed',
        description: 'Darkness and sadness.  Depression, despair, and loneliness.  Often a sign of death or great loss.',
        image: "https://d2lc40okpdverw.cloudfront.net/starr.png",
    },
    {
        id: 96,
        name: 'The Moon, reversed',
        description: 'Confusion.  A crossroads.  Someone is pulled between their conscious logical self and their unconscious intuitive self.',
        image: "https://d2lc40okpdverw.cloudfront.net/moonr.png",
    },
    {
        id: 97,
        name: 'The Sun, reversed',
        description: 'Sadness and dark times.  A loss of innocence.  Someone is disillusioned or dishonest.  Often a sign someone is being manipulated.',
        image: "https://d2lc40okpdverw.cloudfront.net/sunr.png",
    },
    {
        id: 98,
        name: 'Judgement, reversed',
        description: 'Someone is dishonest or untrue to themselves.  Eventually the truth will come out and consequences will be faced.',
        image: "https://d2lc40okpdverw.cloudfront.net/judgementr.png",
      },
    {
        id: 99,
        name: 'The World, reversed',
        description: 'Your world is turned upside down.  One must go on a journey of self-discovery to understand the new world you now live in.',
        image: "https://d2lc40okpdverw.cloudfront.net/worldr.png",
     },
    {
        id: 100,
        name: 'Ace of Wands, reversed',
        description: 'A creative impulse is blocked or ruined.  Someone is not reaching their full potential  Often a sign of frustration or feeling stuck.',
        image: "https://d2lc40okpdverw.cloudfront.net/1wandsr.png",
     },
    {
        id: 101,
        name: 'Two of Wands, reversed',
        description: 'Someone feels confused or stuck in life.  You are uncertain about your future.  You need to take action -- do not just wait for things to happen.',
        image: "https://d2lc40okpdverw.cloudfront.net/2wandsr.png",
     },
    {
        id: 102,
        name: 'Three of Wands, reversed',
        description: 'Problems or delays in plans.  Often a sign of lack of foresight or planning.',
        image: "https://d2lc40okpdverw.cloudfront.net/3wandsr.png",
    },
    {
        id: 103,
        name: 'Four of Wands, reversed',
        description: 'Great change and upheaval.  It can be a difficult time but is also an opportunity for new beginnigns.  It is time to be adaptable.',
        image: "https://d2lc40okpdverw.cloudfront.net/4wandsr.png",
     },
    {
        id: 104,
        name: 'Five of Wands, reversed',
        description: 'Obstacles and challenges.  You may feel scattered and confused.  Put effort into your goals and you will achieve them.',
        image: "https://d2lc40okpdverw.cloudfront.net/5wandsr.png",
       },
    {
        id: 105,
        name: 'Six of Wands, reversed',
        description: 'Setback or failure.  One must work to overcome this temporary challenge.',
        image: "https://d2lc40okpdverw.cloudfront.net/6wandsr.png",
     },
    {
        id: 106,
        name: 'Seven of Wands, reversed',
        description: 'The Seven of Wands is a card that suggests victory is near. It is a time to stand your ground and defend what is yours. This card can also suggest that there are still some challenges to be faced before you can claim your prize.',
        image: "https://d2lc40okpdverw.cloudfront.net/7wandsr.png",
    },
    {
        id: 107,
        name: 'Eight of Wands, reversed',
        description: 'The Eight of Wands is a card of movement and change. It suggests that something is about to happen or is already in motion. This change may be positive or negative, but it is likely to be fast and exciting.',
        image: "https://d2lc40okpdverw.cloudfront.net/8wandsr.png",
     },
    {
        id: 108,
        name: 'Nine of Wands, reversed',
        description: 'The Nine of Wands is a card of resilience and tenacity. It suggests that whatever challenges you are facing, you have the strength and determination to overcome them. This card can also indicate that you may need to take a stand and defend yourself or your beliefs. ',
        image: "https://d2lc40okpdverw.cloudfront.net/9wandsr.png",
     },
    {
        id: 109,
        name: 'Ten of Wands, reversed',
        description: 'The Ten of Wands is a card that suggests that you may be carrying a burden that is too heavy. This may be a physical burden, or it may be an emotional one. Either way, it is important to find a way to lighten your load. This card can also suggest that you are taking on too much responsibility. Try to delegate some of your tasks to others.',
        image: "https://d2lc40okpdverw.cloudfront.net/10wandsr.png",
    },
    {
        id: 110,
        name: 'Page of Wands, reversed',
        description: 'The Page of Wands is a card of new beginnings, of excitement and adventure. It is a card that predicts good news and a time of positive change. This is a time to take risks, to follow your dreams and to seize opportunities. The future looks bright and full of potential.',
        image: "https://d2lc40okpdverw.cloudfront.net/11wandsr.png",
     },
    {
        id: 111,
        name: 'Knight of Wands, reversed',
        description: 'The Knight of Wands is a card that predicts good news and great opportunities in the future. This is a time to seize opportunities and make the most of your talents. You will be able to accomplish a lot and achieve success.',
        image: "https://d2lc40okpdverw.cloudfront.net/12wandsr.png",
    },
    {
        id: 112,
        name: 'Queen of Wands, reversed',
        description: 'The future is full of passion, creativity, and determination. The Queen of Wands is a powerful force that will guide you to your goals. You will be able to achieve anything you set your mind to.',
        image: "https://d2lc40okpdverw.cloudfront.net/13wandsr.png",
     },
    {
        id: 113,
        name: 'King of Wands, reversed',
        description: 'The King of Wands is a powerful force, representing willpower and determination. When this card appears in a tarot reading, it suggests that the querent has the power to manifest their desires and create their own destiny. This is a positive card that predicts success and good fortune in the future.',
        image: "https://d2lc40okpdverw.cloudfront.net/14wandsr.png",
     },
    {
        id: 114,
        name: 'The Ace of Cups, reversed',
        description: 'The Ace of Cups is a card of new beginnings, love, and happiness. It is a very positive card that predicts good things to come in the future. If you are seeking a new relationship, the Ace of Cups is a great card to get. It indicates that you will find true love and happiness in your new relationship.',
        image: "https://d2lc40okpdverw.cloudfront.net/1cupsr.png",
     },
    {
        id: 115,
        name: 'The Two of Cups, reversed',
        description: 'The Two of Cups is a card about love and relationships. It can represent a new relationship, or a strong, existing one. This card can also indicate a need for balance and harmony in a relationship. If you are single, the Two of Cups can represent a new love interest.',
        image: "https://d2lc40okpdverw.cloudfront.net/2cupsr.png",
      },
    {
        id: 116,
        name: 'The Three of Cups, reversed',
        description: 'The Three of Cups is a tarot card that is all about celebration. This is a time to come together with others and enjoy the good things in life. It is a positive card that predicts happy times ahead, full of love, friendship, and good fortune.',
        image: "https://d2lc40okpdverw.cloudfront.net/3cupsr.png",
     },
    {
        id: 117,
        name: 'The Four of Cups, reversed',
        description: 'The Four of Cups is a card that suggests that someone is not paying attention to what is happening around them. This can be a warning for the future, suggesting that the person needs to be more aware of their surroundings in order to avoid potential problems.',
        image: "https://d2lc40okpdverw.cloudfront.net/4cupsr.png",
     },
    {
        id: 118,
        name: 'The Five of Cups, reversed',
        description: 'The Five of Cups is a card that is often seen as a sign of loss. However, this is not always the case. The Five of Cups can also be seen as a sign of change. This change can be either good or bad, but it is often seen as a positive change.',
        image: "https://d2lc40okpdverw.cloudfront.net/5cupsr.png",
    },
    {
        id: 119,
        name: 'The Six of Cups, reversed',
        description: 'The six of cups is a card about nostalgia and looking back on happy memories. It is a reminder that good times have been had in the past, and that although the future may be uncertain, it is important to hold onto the positive things from the past. This card can also indicate that someone from the past may reappear.',
        image: "https://d2lc40okpdverw.cloudfront.net/6cupsr.png",
      },
    {
        id: 120,
        name: 'The Seven of Cups, reversed',
        description: 'The Seven of Cups is a card that is all about choices. You will be presented with many options in your future and it will be up to you to choose which path to take. You may be faced with a difficult decision that will require some soul-searching. This is a time to trust your gut and go with your heart.',
        image: "https://d2lc40okpdverw.cloudfront.net/7cupsr.png",
     },
    {
        id: 121,
        name: 'The Eight of Cups',
        description: 'The Eight of Cups is a card of leaving something behind. It suggests that it may be time to move on from a situation or relationship that is no longer working. This may be a difficult decision, but it is one that will ultimately lead to a better future.',
        image: "https://d2lc40okpdverw.cloudfront.net/8cupsr.png",
    },
    {
        id: 122,
        name: 'The Nine of Cups, reversed',
        description: 'The Nine of Cups is a card of happiness, contentment, and satisfaction. It is a card that predicts that your future will be one of happiness and contentment. You will be able to enjoy your life and all that it has to offer. This is a positive card that predicts a bright future.',
        image: "https://d2lc40okpdverw.cloudfront.net/9cupsr.png",
     },
    {
        id: 123,
        name: 'The Ten of Cups, reversed',
        description: 'The Ten of Cups is the card of happiness, contentment, and fulfilled dreams. This card indicates that your Cup is full and you are ready to enjoy all that life has to offer. You have reached a point where you are able to see the beauty in everyday life and appreciate all that you have. ',
        image: "https://d2lc40okpdverw.cloudfront.net/10cupsr.png",
    },
    {
        id: 124,
        name: 'The Page of Cups, reversed',
        description: 'Someone is being dishonest or manipulative. Often also a sign of insecurity or lack of confidence.  Be careful of the true intentions of others.',
        image: "https://d2lc40okpdverw.cloudfront.net/11cupsr.png",
     },
    {
        id: 125,
        name: 'The Knight of Cups, reversed',
        description: 'Boredom or a lack of passion. Someone is dishonest about their feelings or feeling lonely and isolated from others.',
        image: "https://d2lc40okpdverw.cloudfront.net/12cupsr.png",
      },
    {
        id: 126,
        name: 'The Queen of Cups, reversed',
        description: 'Someone is too trusting and gullible. Be careful of false friends or manipulators who will take advantage of your good nature.',
        image: "https://d2lc40okpdverw.cloudfront.net/13cupsr.png",
     },
    {
        id: 127,
        name: 'The King of Cups, reversed',
        description: 'Relationship problems.  Often a sign of lack of emotional connection, communication, or fulfillment in a relationship.',
        image: "https://d2lc40okpdverw.cloudfront.net/14cupsr.png",
     },
    {
        id: 128,
        name: 'The Ace of Swords, reversed',
        description: 'Problems in the near future.  It is time to be careful and avoid taking risks.  Often a sign a difficult decision needs to be made.',
        image: "https://d2lc40okpdverw.cloudfront.net/1swordsr.png",
     },
    {
        id: 129,
        name: 'The Two of Swords, reversed',
        description: 'Someone is not thinking clearly.  You are being manipulated or blinded by your own emotions, leading to bad decisions and painful consequences.  Often a sign someone is in denial.',
        image: "https://d2lc40okpdverw.cloudfront.net/2swordsr.png",
     },
    {
        id: 130,
        name: 'The Three of Swords, reversed',
        description: 'Heartbreak and pain.  A great loss or betrayal.  You must take time to heal and work out your complicated emotions.',
        image: "https://d2lc40okpdverw.cloudfront.net/3swordsr.png",
     },
    {
        id: 131,
        name: 'The Four of Swords, reversed',
        description: 'Rest and relief.  You should take time for yourself to heal physically and emotionally.  It is also a time to reflect on the past and learn from mistakes.  You will awaken refreshed and full of creative energy.',
        image: "https://d2lc40okpdverw.cloudfront.net/4swordsr.png",
    },
    {
        id: 132,
        name: 'The Five of Swords, reversed',
        description: 'Major change in a situation. You are wise enough to avoid unnecessary conflict or destructive emotions.  You will have peace and resolution, even if the outcome is not what you expected.',
        image: "https://d2lc40okpdverw.cloudfront.net/5swordsr.png",
     },
    {
        id: 133,
        name: 'The Six of Swords, reversed',
        description: 'Major life change.  It will be difficult, but the outcome will be worth it and you will come out stronger.',
        image: "https://d2lc40okpdverw.cloudfront.net/6swordsr.png",
    },
    {
        id: 134,
        name: 'The Seven of Swords, reversed',
        description: 'Future success from bold action.  It is time to take advantage of opportunities that come your way.  The rewards will be worth it.',
        image: "https://d2lc40okpdverw.cloudfront.net/7swordsr.png",
     },
    {
        id: 135,
        name: 'The Eight of Swords, reversed',
        description: 'You are freed from whatever was holding you back.  Your period of stress, insecurity, and self-imposed limitation is over.  It is time to take risks.  The rewards will be worth it.',
        image: "https://d2lc40okpdverw.cloudfront.net/8swordsr.png",
    },
    {
        id: 136,
        name: 'The Nine of Swords, reversed',
        description: 'Stress and suffering.  Someone feels stuck in a dark place and full of worry and fear.  This is only a temporary situation.  With time and perseverence, you will find peace again.',
        image: "https://d2lc40okpdverw.cloudfront.net/9swordsr.png",
     },
    {
        id: 137,
        name: 'The Ten of Swords, reversed',
        description: 'Relief from troubles.  You have overcome a problem and grown stronger and wiser.  You may now put your problems behind you.',
        image: "https://d2lc40okpdverw.cloudfront.net/10swordsr.png",
    },
    {
        id: 138,
        name: 'The Page of Swords, reversed',
        description: 'A major problem or setback.  You will overcome it if you remain careful, resourceful, and brave.  A test of mettle.',
        image: "https://d2lc40okpdverw.cloudfront.net/11swordsr.png",
     },
    {
        id: 139,
        name: 'The Knight of Swords, reversed',
        description: 'Foolish, impulsive action.  Someone is taking a dangerous risk or acting out of anger and frustration.  It is important to think through things calmly.',
        image: "https://d2lc40okpdverw.cloudfront.net/12swordsr.png",
     },
    {
        id: 140,
        name: 'The Queen of Swords, reversed',
        description: 'A cold, manipulative woman or someone who judges others harshly.  Can also be a sign of feeling trapped, depressed, or losing control over a situation.',
        image: "https://d2lc40okpdverw.cloudfront.net/13swordsr.png",
     },
    {
        id: 141,
        name: 'The King of Swords, reversed',
        description: 'Someone is lost or confused.  It is a tough time and you are not in control.  A manipulator will soon lose their power.',
        image: "https://d2lc40okpdverw.cloudfront.net/14swordsr.png",
    },
    {
        id: 142,
        name: 'The Ace of Coins, reversed',
        description: 'A temporary loss of wealth.  Good luck soon after, but it will take hard work and optimism in the face of challenges.',
        image: "https://d2lc40okpdverw.cloudfront.net/1coinsr.png",
    },
    {
        id: 143,
        name: 'The Two of Coins, reversed',
        description: 'Difficulty with money or responsibilities.  Someone is overspending or taking on too much work.  It is time to balance your budget and time.',
        image: "https://d2lc40okpdverw.cloudfront.net/2coinsr.png",
      },
    {
        id: 144,
        name: 'The Three of Coins, reversed',
        description: 'Someone is stuck in life.  You may feel there is no way out or that you are not using your talents to their fullest potential.  It is time to take a closer look at life and what you need to change.',
        image: "https://d2lc40okpdverw.cloudfront.net/3coinsr.png",
     },
    {
        id: 145,
        name: 'The Four of Coins, reversed',
        description: 'Greed or money troubles.  Struggle to make ends meet or unexpected expenses.  It is time to get creative about your budget and career.',
        image: "https://d2lc40okpdverw.cloudfront.net/4coinsr.png",
     },
    {
        id: 146,
        name: 'The Five of Coins, reversed',
        description: 'Anxiety about finances.  Temporary money troubles that will be solved soon with hard work and perseverance.',
        image: "https://d2lc40okpdverw.cloudfront.net/5coinsr.png",
     },
    {
        id: 147,
        name: 'The Six of Coins, reversed',
        description: 'Financial difficulty.  Overspendinng, poor investment, or being cheated out of pay or inheritance.  But you will soon overcome this.',
        image: "https://d2lc40okpdverw.cloudfront.net/6coinsr.png",
    },
    {
        id: 148,
        name: 'The Seven of Coins, reversed',
        description: 'Isolation, loneliness, or lack of confidence.  Someone is too focused on material possessions and not enough on relationships.',
        image: "https://d2lc40okpdverw.cloudfront.net/7coinsr.png",
     },
    {
        id: 149,
        name: 'The Eight of Coins, reversed',
        description: 'A lack of progress.  You feel unproductive, stuck, or not as successful as you hoped.  But you will soon break free and create the life you desire.',
        image: "https://d2lc40okpdverw.cloudfront.net/8coinsr.png",
     },
    {
        id: 150,
        name: 'The Nine of Coins, reversed',
        description: 'Financial insecurity.  It is time to be careful with money and budget.  At worst, this means greed, selfishness, and lack of generosity.',
        image: "https://d2lc40okpdverw.cloudfront.net/9coinsr.png",
    },
    {
        id: 151,
        name: 'The Ten of Coins, reversed',
        description: 'Greed and materialism.  At worst, your obsession with money will lead to a major financial setback.  Be humble and levelheaded.',
        image: "https://d2lc40okpdverw.cloudfront.net/10coinsr.png",
     },
    {
        id: 152,
        name: 'The Page of Coins, reversed',
        description: 'Hardship and financial trouble.  It is time to be careful with money and responsible in your work and home life, even if it is stressful.',
        image: "https://d2lc40okpdverw.cloudfront.net/11coinsr.png",
     },
    {
        id: 153,
        name: 'The Knight of Coins, reversed',
        description: 'Someone is stuck.  You may feel frustrated or not in control of your own destiny. Perhaps it is time to take a risk and change.',
        image: "https://d2lc40okpdverw.cloudfront.net/12coinsr.png",
      },
    {
        id: 154,
        name: 'The Queen of Coins, reversed',
        description: 'Loss of money or material possessions.  Debt or financial difficulty.',
        image: "https://d2lc40okpdverw.cloudfront.net/13coinsr.png",
      },
    {
        id: 155,
        name: 'The King of Coins, reversed',
        description: 'Financial problems.  Often a sign of job loss, unexpected bills, or a anxiety about finances.',
        image: "https://d2lc40okpdverw.cloudfront.net/14coinsr.png",
     },
]