
export const cards = [
    {
        id: 0,
        name: 'The Fool',
        description: 'The image of new beginnings, innocence, and adventure.  A new opportunity, journey, or relationship.',
        longdescription: 'The Fool is one of the most important cards in the tarot deck. It is the first card in the Major Arcana, and it represents new beginnings, innocence, and possibilities. The Fool is a reminder that we are all on a journey, and that the journey is full of ups and downs. Sometimes we will make mistakes, but we must always keep moving forward. The Fool can represent the querent in a reading. It can represent someone who is starting a new chapter in their life, or someone who is feeling lost and uncertain. The Fool can also represent a decision that the querent will have to make. This decision may be a difficult one, but it is one that will lead to growth and new experiences. The Fool can predict that the querent will have many new experiences in their future. They will learn new things, and they will make mistakes. But, as long as they stay on their journey, they will eventually find success. When the Fool is reversed, it can represent a fear of change. The querent may be afraid to take risks, or they may be stuck in their ways. This is a time when the querent needs to take a leap of faith and trust that the universe will guide them to where they need to be.',
        image: "https://d2lc40okpdverw.cloudfront.net/fool.png",
        yesno: "Yes.",
    },
    {
        id: 1,
        name: 'The Magician',
        description: 'Transformation and major life change. It predicts that you will be able to make a big change in your life, and that this change will be for the better. This is a great card to get if you are feeling stuck in a rut and need some fresh start.',
        longdescription: 'The Magician tarot card is one of the most popular tarots among querents. It represents an ability to create their own reality. The Magician is a master of illusion and can make the impossible seem possible. This tarot is about manifesting desires and using personal power to create the life they want to live. The reversed Magician can represent a lack of personal power or a failure to manifest desires. It can also indicate a querent who is being misled or is living in a state of denial.  The querent who draws this card is likely to be in a period of change and transformation. They may be starting a new project or undertaking a new challenge. The Magician represents the ability to make their dreams a reality. The card predicts success and abundance for the querent, as long as they are willing to put in the work. When the Magician is reversed, it can indicate that the querent is not using their own power to manifest their desires. They may be relying on others too much, or may be afraid to take control of their own lives. The reversed Magician can also indicate that the querent is not living up to their potential. If the querent is not careful, they may miss out on opportunities for growth and success.',
        image: "https://d2lc40okpdverw.cloudfront.net/magician.png",
        yesno: "Yes.",
    },
    {
        id: 2,
        name: 'The High Priestess',
        description: 'Mystery and intuition. It is a beautiful card that represents the feminine side of the divine. The High Priestess is a wise and compassionate woman who is able to see into the future. ',
        longdescription: 'The High Priestess is one of the most enigmatic cards in the tarot deck. She is the guardian of the unconscious mind, and represents the feminine principle of intuition and receptivity. The High Priestess is a card of mystery, magic, and hidden knowledge. The High Priestess is a card that suggests that you are in touch with your intuition and inner wisdom. You are able to see beyond the surface of things, and have access to hidden knowledge. The High Priestess is a card that predicts that you will have success in your endeavors. You are able to tap into your inner wisdom and intuition to guide you to success. The High Priestess is a card of magic and mystery, and her reversed form suggests that you may be keeping some hidden knowledge to yourself. Be careful not to withhold information that could be helpful to others.',
        image: "https://d2lc40okpdverw.cloudfront.net/highpriestess.png",
        yesno: "Yes.",
    },
    {
        id: 3,
        name: 'The Empress',
        description: 'Creation and nurturing. It predicts a future of abundance and fertility, with plenty of opportunities for growth and expansion.',
        longdescription: 'In a reading, The Empress tarot card can represent a number of things. Most often, it is a sign of fertility, abundance, and creation. It can also indicate that the querent is in a position of power, or is about to achieve a position of power. The Empress can also represent your mother, or a mother figure. When The Empress is reversed, it can mean that the querent is out of balance. They may be overindulging, or may be neglecting their responsibilities. The reversed Empress can also indicate a lack of creativity, or a lack of fertility.The Empress is a positive card, and she usually predicts good things for the future. If you are asking a question about love, The Empress is a good sign that your relationship is strong and will continue to grow. If you are asking a question about your career, The Empress is a good sign that you will be successful in your pursuits.',
        image: "https://d2lc40okpdverw.cloudfront.net/empress.png",
        yesno: "Yes.",
    },
    {
        id: 4,
        name: 'The Emperor',
        description: 'Power and conquering. It predicts that you will have the strength and power to overcome any obstacle in your way. You will be able to achieve anything you set your mind to.',
        longdescription: 'The Emperor is the ruler of the tarot, representing strength, authority, and structure. He is a powerful figure who brings order to chaos and stands for all that is just and fair. The Emperor is a positive force in the life of the querent, predicting success, stability, and progress. He is a symbol of the traditional values of family, community, and country. When the Emperor is reversed, it indicates a loss of power or control. The querent may be experiencing a time of upheaval or chaos. The Emperor reversed can also represent a need for change or a challenge to the status quo.  Someone may be feeling powerless and out of control. The reversed Emperor can also represent someone in their life who is abuse their power or who is being too controlling.',
        image: "https://d2lc40okpdverw.cloudfront.net/emperor.png",
        yesno: "Yes.",
     },
    {
        id: 5,
        name: 'The Hierophant',
        description: 'Traditional wisdom and knowledge for the future. It is a beautiful card that represents the importance of learning and understanding the past in order to make the future brighter.',
        longdescription: 'The Hierophant is one of the most important cards in the tarot deck because it represents knowledge, spiritual enlightenment, and religious teachings.  This card can represent someone who is a teacher or a counselor, someone who is knowledgeable and can offer guidance.  The Hierophant can also represent a spiritual path, and their relationship to religion or spirituality. If the querent is asking about their spiritual path, the Hierophant can represent traditional religious teachings, or more esoteric knowledge. The Hierophant can also represent the need to seek guidance from a mentor or teacher. If the Hierophant is reversed, it can represent a rejection of traditional knowledge or teachings. The querent may be questioning their faith, or they may be exploring more unorthodox beliefs. The reversed Hierophant can also represent a need to strike out on your own and find their own path, rather than following the crowd.',
        image: "https://d2lc40okpdverw.cloudfront.net/hierophant.png",
        yesno: "Yes.",
     },
    {
        id: 6,
        name: 'The Lovers',
        description: 'Love and romance. Romantic bliss and joyful fulfillment in a new relationship or renewed passion in an existing relationship.',
        longdescription: 'In a reading, The Lovers card can represent many things. Often, it indicates a choice that must be made. This choice is usually between two options that are equally appealing, and it can be a difficult one to make. The Lovers card can also represent a new relationship, or a relationship that is going through a major change. This card can be a very positive sign, indicating that the querent is about to experience some good fortune in their love life. If the querent is single, The Lovers card predicts that they will soon meet someone special. If the querent is in a relationship, this card indicates that the relationship will soon blossom and reach a new level of intimacy.When The Lovers card is reversed, it often indicates that the querent is avoiding making a decision. They may be afraid of making the wrong choice, or they may be unable to choose between two equally appealing options. This can lead to a feeling of being stuck, and it may be difficult to move forward in life. If the querent is single, it may indicate that they are afraid of commitment. If the querent is in a relationship, it may indicate that the relationship is not progressing and may even be regressing.',
        image: "https://d2lc40okpdverw.cloudfront.net/lovers.png",
        yesno: "Yes.",
    },
    {
        id: 7,
        name: 'The Chariot',
        description: 'Victory and great things for the future. It represents success, victory, and triumph. It is a card of strength and determination. The Chariot is a force to be reckoned with. It is a sign of good things to come.',
        longdescription: 'The Chariot card is one of the most powerful cards in the tarot deck. It is a card that represents triumph, victory, and success. It is a card that predicts great things for the future, and when it is reversed, it can indicate problems or setbacks. The Chariot card is a symbol of strength and determination. It represents the ability to overcome any obstacle and achieve success. The card is also a reminder that we must be in control of our own destiny. We must be the master of our own fate. The Chariot card can also be a warning against reckless behavior. It is important to remember that we must be in control of our actions and our destiny. We must be careful not to let our emotions get the best of us. When the Chariot card is reversed, it can indicate problems or setbacks. It can also be a warning against letting our emotions get the best of us. We must remember to stay in control of our own destiny.',
        image: "https://d2lc40okpdverw.cloudfront.net/chariot.png",
        yesno: "Yes.",
    },
    {
        id: 8,
        name: 'Strength',
        description: 'Great strength and fortitude in the face of adversity. With this card comes the ability to overcome any obstacle and the courage to face any challenge. The Strength tarot card is a reminder that we are all capable of great things if we set our minds to it.',
        longdescription: 'The Strength tarot card is one of the most powerful cards in the deck. It represents strength, power, and determination. This card can be a great asset in the life of the querent, predicting success and victory in their future. When the Strength card is upright, it is a positive sign. It indicates that the querent has the strength and power to overcome any challenges they may face. This card predicts success and victory in the future. When the Strength card is reversed, it is a negative sign. It indicates that the querent may be facing some challenges that they are not prepared to face. This card predicts that the querent may have to face some difficult obstacles in their future.',
        image: "https://d2lc40okpdverw.cloudfront.net/strength.png",
        yesno: "Yes.",
    },
    {
        id: 9,
        name: 'The Hermit',
        description: 'Introspection and self-reflection. It is a time to take stock of your life and figure out what is truly important to you. This can be a difficult and challenging process, but it is also a time of great personal growth. ',
        longdescription: 'The Hermit is a tarot card that is often associated with introspection, contemplation, and withdrawal from the material world. It is a card that suggests that the querent is in a period of reflection and self-awareness. The Hermit is often seen as a positive card, as it suggests that the querent is taking the time to reflect on their life and make changes that are necessary for personal growth.  When the Hermit is seen in a tarot reading, it often suggests that the querent is in a period of introspection. This is a time for the querent to be alone with their thoughts and to reflect on their life. The Hermit can also suggest that the querent is facing a problem that they need to solve on their own. The Hermit is a card that suggests that the querent is in a period of reflection and self-awareness.  If the Hermit is surrounded by positive cards, it suggests that the querent is on a positive path and is making progress. However, if the Hermit is surrounded by negative cards, it suggests that the querent is facing challenges and may need to make some changes in their life. ',
        image: "https://d2lc40okpdverw.cloudfront.net/hermit.png",
        yesno: "Wait and think about it.  Then yes.",
    },
    {
        id: 10,
        name: 'The Wheel of Fortune',
        description: 'Change, new beginnings, and the cyclical nature of life. It is a reminder that nothing stays the same forever, and that good fortune and bad fortune are both part of the human experience. The Wheel of Fortune is a reminder to stay flexible and open to change, as it is the only constant in life.',
        longdescription: 'The Wheel of Fortune is one of the most well-known tarot cards, and for good reason. It is a powerful symbol of the ups and downs that we all experience in life. The wheel itself is a symbol of the cyclical nature of life, and the fact that what goes up must come down. The figures on the wheel represent the different aspects of our lives that are in constant flux. The black and white colors represent the duality of life, and how everything is connected.  This card can represent a time of change in life. It is a time to be open to new possibilities and to take risks. The future is uncertain, but that is what makes it exciting. The reversed Wheel of Fortune can represent a time when the querent is feeling stuck. They may be going through a difficult time, and it may seem like things will never change. But even in the darkest of times, the Wheel of Fortune reminds us that life is always moving forward. Everything is connected, and everything happens for a reason.',
        image: "https://d2lc40okpdverw.cloudfront.net/wheel.png",
        yesno: "Yes.",
     },
    {
        id: 11,
        name: 'Justice',
        description: 'Balance, harmony, and fairness. It predicts that the future will bring these things into your life in some way. Justice is about making things right, and this card suggests that you will be able to do that in your own life.',
        longdescription: 'The Justice tarot card is one of the most well-known and popular tarot cards. It is often seen as a positive card, representing balance, fairness, and the ability to see both sides of a situation. When reversed, however, it can represent injustice, imbalance, and unfairness.  The Justice tarot card can also predict that the querent will have to make some tough decisions in the future. This is not necessarily a bad thing, but it does mean that the querent will have to weigh their options carefully before making any decisions.  If the Justice tarot card is reversed, it can represent injustice, imbalance, and unfairness. This can be in your personal life, or it can be in the wider world. ',
        image: "https://d2lc40okpdverw.cloudfront.net/justice.png",
        yesno: "Yes, but make sure you're doing the right thing.",
    },
    {
        id: 12,
        name: 'The Hanged Man',
        description: 'One is caught between two choices. It is a time of indecision and confusion. This card advises you to take a step back, to look at the bigger picture, and to be patient. The Hanged Man also suggests that you let go of what is no longer serving you. This is a time of transition and rebirth.',
        longdescription: 'The Hanged Man is one of the most intriguing cards in the tarot deck. It is a card that can represent many different things in life, and it can predict many different things for the future. The Hanged Man is a card that is often associated with change, transformation, and new beginnings. It is a card that can represent a person who is at a crossroads in their life, and it is a card that can predict a new phase in life. The Hanged Man can also represent a person who is facing a difficult situation or challenge. This card can represent a person who is feeling stuck in their life, and it can represent a person who is going through a difficult time. The Hanged Man can also be a positive card, representing a person who is about to make a positive change in their life. When The Hanged Man is reversed, it can represent a person who is resisting change. It can also represent a person who is stuck in a negative cycle. The Hanged Man reversed can also represent a person who is facing a difficult decision.',
        image: "https://d2lc40okpdverw.cloudfront.net/hangedman.png",
        yesno: "Yes.",
     },
    {
        id: 13,
        name: 'Death',
        description: 'Death, rebirth, change, and transformation. It suggests that something major is ending in your life, but also that new beginnings are on the horizon. This could be a time of great upheaval, but also of great opportunity. The future looks bright, but it will be full of challenges and obstacles to overcome.',
        longdescription: 'The Death card is one of the most feared cards in a tarot deck. It is often seen as a predictor of doom and gloom, but it can also represent new beginnings. The Death card can represent the end of a cycle, the death of a relationship, the death of a job, or the death of a way of life. It can also represent the end of an era, or the end of a chapter in your life.  The Death card can be a frightening card to see in a reading, but it is important to remember that death is not always a bad thing. Death can be a natural and necessary part of life. It can be a sign that it is time to let go of something that is no longer serving you. The Death card can also be a sign that something new is about to begin.   If the Death card is reversed, it can represent a fear of change. It can also represent a resistance to change. The reversed Death card can be a sign that you are holding on to something that is no longer serving you. It can also be a sign that you are afraid to let go of something that is familiar, even if it is no longer working for you.   The Death card can be a difficult card to interpret, but it is important to remember that death is not always a bad thing. Death can be a natural and necessary part of life. It can be a sign that it is time to let go of something that is no longer serving you. The Death card can also be a sign that something new is about to begin.',
        image: "https://d2lc40okpdverw.cloudfront.net/death.png",
        yesno: "No.",
    },
    {
        id: 14,
        name: 'Temperance',
        description: 'Balance and harmony in life. It is about learning to control your emotions and not letting them control you. This card predicts that you will find a way to strike a perfect balance in your life, and that you will be able to control your destiny.',
        longdescription: 'The Temperance card is all about balance, moderation, and harmonious living. It represents a need for the querent to find a middle ground between two extremes. This may be a time of transition or change, when the querent is called to find a new way of being. The key is to stay calm and focused, and to trust that everything will work out in the end.  The Temperance card can also predict a time of good fortune and growth. If the querent is able to maintain their balance, they will be rewarded with abundance. This is a card of hope and promise, telling the querent that they are on the right track. Things may not be easy, but if they can stay the course, they will eventually reach their goals.  When the Temperance card is reversed, it can indicate a lack of balance in life. This may be a time of chaos and discord, when the querent is struggling to maintain control. The reversed Temperance card can also suggest that the querent is being too rigid in their thinking, and that they need to be more flexible. If the querent can find a way to restore balance, they will be able to move forward again.', 
        image: "https://d2lc40okpdverw.cloudfront.net/temperance.png",
        yesno: "Yes.",
     },
    {
        id: 15,
        name: 'The Devil',
        description: 'Fears, addictions, and desires. It urges us to face our demons and to overcome them. The card predicts that we will be challenged in the future, but we have the strength to overcome these obstacles.',
        longdescription: 'The Devil is a powerful and feared tarot card. It represents our primal desires and urges, those things we are ashamed of and try to keep hidden. It is the card of addiction and obsession, of being controlled by our darker impulses. The Devil can represent a person who is manipulative and dangerous, someone who is temptation personified. It can also indicate a situation in which we are feeling trapped or controlled. When the Devil card is reversed, it can mean that we are finally starting to break free from our addictions and obsessions. We are learning to control our darker impulses. This can be a difficult and painful process, but it is one that will ultimately lead to liberation. The reversed Devil can also represent someone who is no longer able to control or manipulate others. They have lost their power over us. No matter what the Devil card means in our lives, it is always a powerful symbol. It represents the shadow side of our nature, the part of us that we try to keep hidden. It is a reminder that we all have a dark side, but that does not mean we have to be controlled by it. We can learn to control our own destiny, to be the masters of our own fate.',
        image: "https://d2lc40okpdverw.cloudfront.net/devil.png",
        yesno: "No.",
      },
    {
        id: 16,
        name: 'The Tower',
        description: 'Great upheaval and chaos in the future. The meaning of the card is that everything will come crashing down, but from the rubble will rise a new and better version of yourself.',
        longdescription: 'In tarot, The Tower is a Major Arcana card that represents chaos, upheaval, and radical change. It is a card of upheaval and chaos because it represents a sudden, unexpected event that upends your life as you know it. This event can be anything from a natural disaster to a relationship break-up. The important thing to remember is that The Tower is a card of radical change, and it always brings with it an element of surprise.  The Tower can be a difficult card to interpret because it is so full of potential energy. On the one hand, this energy can be channeled into positive change, but on the other hand, it can also lead to destruction. The key is to remember that The Tower is a card of radical change, and it always brings with it an element of surprise. The key is to be prepared for the unexpected and to embrace change when it comes. The Tower reversed can indicate that you are resisting change. This resistance may be due to fear or a lack of understanding. The key is to remember that The Tower is a card of radical change, and it always brings with it an element of surprise. The key is to be open to change, even when it is scary.  The Tower can be a difficult card to interpret, but it is important to remember that the key is to be prepared for the unexpected and to embrace change when it comes.',
        image: "https://d2lc40okpdverw.cloudfront.net/tower.png",
        yesno: "No.",
    },
    {
        id: 17,
        name: 'The Star',
        description: 'Hope, faith, and endless possibility. It predicts that good things are on the horizon, and that your wishes may come true. This is a time to have faith in yourself and your abilities, as success is within reach. The future looks bright and full of potential, so let your light shine and reach for the stars.',
        longdescription: 'The Star is one of the most beautiful and intriguing cards in the tarot deck. It is full of hope and promise, but also mystery and magic. This card represents a time of new beginnings, fresh start, and hope for the future. It is a time when we are reaching for the stars and dreaming big.  This card can represent a new job, a new relationship, a new baby, or any other new beginning in our lives. It is a time of hope and possibility. We are open to new possibilities and ready to take risks. This is a time of growth and expansion.  The Star can also predict good fortune and luck in the future. This is a time when things are aligning in our favor and we are able to manifest our desires. We are attracting all the right circumstances and people into our lives. Everything feels possible and within reach.  When The Star is reversed, it can represent a time of doubt and fear. We may be feeling lost and uncertain. We may be second-guessing our decisions and questioning our path. This is a normal part of the journey, but it is important to remember that the future is still full of hope and possibility. Keep your head up and have faith that things will work out in the end.',
        image: "https://d2lc40okpdverw.cloudfront.net/star.png",
        yesno: "Yes.",
    },
    {
        id: 18,
        name: 'The Moon',
        description: 'Secrets, mysteries, intuition, and psychic ability. It predicts that the future will be full of surprises and you will need to rely on your intuition to guide you. The Moon also represents imagination, so expect your future to be full of creativity and new ideas.',
        longdescription: 'The Moon is a tarot card that is often associated with intuition, emotion, and the subconscious mind. It is often seen as a representation of the feminine principle, and is often considered to be a negative card. The Moon can indicate a time of confusion, deception, and even madness. When the Moon is reversed, it can indicate a time of clarity and peace.  The Moon is a card that is often associated with the element of water. This is because water is often seen as a symbol of the emotions. The Moon is also associated with the astrological sign of Cancer. Cancer is a sign that is known for its emotional nature. The Moon is also associated with the planet Neptune. Neptune is a planet that is often associated with intuition and the subconscious mind.  The Moon is a card that often indicates a time of change. This change can be both good and bad. The Moon often represents a time when we are forced to face our fears. The Moon can also indicate a time of great creativity. This is because the Moon is often seen as a symbol of the imagination.  The Moon is a card that can be both positive and negative. It all depends on how you interpret the card. The Moon can represent a time of great change, both good and bad. It can also indicate a time of great creativity.',
        image: "https://d2lc40okpdverw.cloudfront.net/moon.png",
        yesno: "Yes.",
    },
    {
        id: 19,
        name: 'The Sun',
        description: 'Joy, fulfillment, happiness, and success. It is a symbol of good fortune and represents the power of the sun to bring positive change. The Sun is a positive card that suggests that the querent will achieve their goals and enjoy good health and fortune.',
        longdescription: 'The Sun is one of the most positive cards in the tarot deck. It is associated with happiness, vitality, success, and good fortune. The Sun card predicts that you will experience these things in your life. The Sun card also represents new beginnings, so if you have been feeling stuck, this is a good time to make a change. The Sun card reversed can indicate that you are experiencing some difficulties in your life. However, these difficulties are temporary and you will eventually overcome them. The Sun card also suggests that you should take some time to enjoy your life and have fun.',
        image: "https://d2lc40okpdverw.cloudfront.net/sun.png",
        yesno: "Yes.",
    },
    {
        id: 20,
        name: 'Judgement',
        description: 'Actions have consequences. It predicts that we will be called to account for our choices in the future, and that we must be prepared to face the consequences of our actions.',
        longdescription: 'The tarot card known as "Judgement" is one of the most controversial and difficult to interpret cards in the deck. To some, it represents final judgement and the end of all things, while others see it as a card of rebirth and new beginnings. No matter what your interpretation is, one thing is certain: the Judgement card is not to be taken lightly. This card can represent a time of major decisions in your life. It is a time to take stock of your life and consider what you have accomplished. This is not a time to be afraid of making changes, but rather a time to embrace them. The Judgement card can also represent a time of upheaval or chaos in your life. This is not necessarily a bad thing, as it can lead to positive change. However, it is important to be prepared for the challenges that may come your way. The Judgement card can also be a sign of new beginnings. If you have been feeling stuck in a rut, this card can represent a fresh start. This is a time to let go of the past and move forward into the future. It is also a time to forgive yourself for your mistakes and learn from them. The Judgement card can be a difficult card to interpret, but ultimately it is a sign of hope and change.',
        image: "https://d2lc40okpdverw.cloudfront.net/judgement.png",
        yesno: "Yes.",
      },
    {
        id: 21,
        name: 'The World',
        description: 'The fulfillment of something great.  The future will be full of new and wonderful experiences. The world is a place full of possibility and hope, and this card predicts that the future will be full of possibilities for everyone.',
        longdescription: 'The World is the final card in the Major Arcana and is often interpreted as the culmination of the journey of the Fool. The World is a symbol of completion, of wholeness, and of success. It is a card that represents the achievement of goals and the realization of dreams, as well as satisfaction and completion. This card suggests that you have reached a point in your life where you have accomplished what you set out to do.  ​​When The World is reversed, it can mean that a person is not yet finished with their journey. They may still have some unfinished business to attend to. Alternatively, it can suggest that a person is not yet ready to receive all that they have worked for. They may need to put in a little more effort before they can fully enjoy the fruits of their labor.',
        image: "https://d2lc40okpdverw.cloudfront.net/world.png",
        yesno: "Yes.",
     },
]